[package]
name = "deltadefi"
version = "0.0.4"
edition = "2021"
license = "Apache-2.0"
description = "The Rust SDK for DeltaDeFi"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
whisky = "1.0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.79"
reqwest = "0.12.5"

[profile.release]
# Tell `rustc` to optimize for small code size.
codegen-units = 1
opt-level = "s"
incremental = true
lto = true

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }